repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.260'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --line-length=120]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: .+/snapshots/.+
        additional_dependencies:
          - mypy-extensions
          - freezegun
          - types-python-dateutil
          - types-PyYAML
          - types-simplejson
          - types-redis
          - types-requests
exclude: |
  (?x)(
    .*\/notebooks\/.*\.py|
    \.ipynb|
    \.venv
  )
