model_list:
  # For response gathering
  - model_name: "claude-3-sonnet-20240229"
    litellm_params:
      model: "anthropic/claude-3-sonnet-20240229"
      api_key: "os.environ/ANTHROPIC_API_KEY"
      batch_size: 20  # Enable batch API with max 20 messages per batch

  # For evaluation models
  - model_name: "gpt-4"
    litellm_params:
      model: "openai/gpt-4"
      api_key: "os.environ/OPENAI_API_KEY"
      
  - model_name: "gemini-pro"
    litellm_params:
      model: "vertex_ai/gemini-pro"
      project_id: "os.environ/VERTEX_PROJECT"
      location: "os.environ/VERTEX_LOCATION"

general_settings:
  # Enable detailed logging for debugging
  debug: true
  # Set a master key for proxy authentication
  master_key: "os.environ/LITELLM_MASTER_KEY"
