model_list:
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: your-openai-key

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: your-openai-key

  - model_name: claude-2
    litellm_params:
      model: claude-2
      api_key: your-anthropic-key

  - model_name: gemini-pro
    litellm_params:
      model: gemini-pro
      api_key: your-google-key

  - model_name: palm-2
    litellm_params:
      model: palm-2
      api_key: your-palm-key

  - model_name: azure-gpt-4
    litellm_params:
      model: azure/gpt-4
      api_key: your-azure-key
      api_base: your-azure-endpoint
      api_version: "2023-07-01-preview"

  - model_name: azure-gpt-35
    litellm_params:
      model: azure/gpt-35-turbo
      api_key: your-azure-key 
      api_base: your-azure-endpoint
      api_version: "2023-07-01-preview"

  - model_name: bedrock-claude
    litellm_params:
      model: bedrock/anthropic.claude-v2
      aws_access_key_id: your-aws-access-key
      aws_secret_access_key: your-aws-secret-key
      aws_region_name: your-aws-region

litellm_settings:
  drop_params: True
  set_verbose: True
  cache: True
  cache_params:
    type: redis
    host: localhost
    port: 6379
    
environment_variables:
  OPENAI_API_KEY: "your-openai-key"
  ANTHROPIC_API_KEY: "your-anthropic-key"
  GOOGLE_API_KEY: "your-google-key"
  AZURE_API_KEY: "your-azure-key"
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
